---
abstract: 'A pragma to use the C3 method resolution order algortihm'
author:
  - 'Stevan Little, <stevan@iinteractive.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.47
configure_requires:
  ExtUtils::CBuilder: 0.27
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Class-C3
no_index:
  directory:
    - inc
    - t
requires:
  Algorithm::C3: 0.07
  Scalar::Util: 0
  perl: 5.6.2
resources:
  license: http://dev.perl.org/licenses/
version: 0.23_01
